### ISSUE TITLE
Add Chromista kingdom to the biological vocabulary

### ISSUE THREAD

**Issue by dannymandel** [isamplesorg/vocabularies#17]
We have Chromista in our taxon name cache:

```
isb_2=> select distinct kingdom from taxonomyname;
    kingdom     
----------------
 Archaea
 Bacteria
 Viruses
 incertae sedis
 Fungi
 Chromista
 Animalia
 Plantae
 Protozoa
(9 rows)
```

And a number of GEOME records have this as their kingdom.  We should add it to https://vocabs.ardc.edu.au/repository/api/lda/isamples/biology-extension-basic-taxon-classes-for-biologic/1-0/resource?uri=https://w3id.org/isample/biology/biosampledfeature/1.0/biologicentityvocabulary

**Comment by smrgeoinfo** [comment]
suggestion from discussion--
add chromista to taxonomy,  subclass of Eucaryote  note possible overlap with Algae, protista, 
SEE catalog of life taxonomic backbone, GBIF; There are various identifiers. 
used in GEOME (GEOME vocabs are controlled by teams, phyla more controlled that kingdom).   Assignments are uncertain and change.  
Another situation where recording the verbatim taxa, and assigned to most specific subsuming class in controlled vocab.

**Comment by smrgeoinfo** [comment]
I'm going to merge this into biology_extension main.  see https://github.com/isamplesorg/metadata_profile_biology/pull/1

**Comment by smrgeoinfo** [comment]
done, closing
